include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = VibeTendiesPrefs
VibeTendiesPrefs_FILES = RootListController.m
VibeTendiesPrefs_INSTALL_PATH = /Library/PreferenceBundles
VibeTendiesPrefs_FRAMEWORKS = UIKit PhotosUI
VibeTendiesPrefs_PRIVATE_FRAMEWORKS = Preferences
VibeTendiesPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
